import type { Status } from "@/types";

export const statusLabels: Record<Status, string> = {
  active: "نشط",
  inactive: "غير نشط",
  pending: "قيد الانتظار",
  approved: "معتمد",
  rejected: "مرفوض",
  returned: "مرتجع",
  draft: "مسودة",
  completed: "مكتمل",
  cancelled: "ملغي",
  suspended: "موقوف",
  overdue: "متأخر",
  submitted: "مقدم",
  under_review: "قيد المراجعة",
  inspection: "قيد الفحص",
  posted: "مرحل",
  received: "مستلم",
  executed: "منفذ",
  partially_paid: "مسدد جزئياً",
  in_transit: "قيد النقل",
  damaged: "تالف",
  reserved: "محجوز",
  delivered: "تم التسليم",
  in_progress: "قيد التنفيذ",
  failed: "فشل",
  closed: "مغلق",
  locked: "مقفل",
  issued: "مسلمة",
  transferred: "منقولة",
  paid: "مسدد",
  partial: "مسدد جزئياً",
  unpaid: "غير مسدد",
  converted: "تم التحويل",
  paused: "متوقف مؤقتاً",
  synced: "متزامن",
};

export type BadgeTone = "success" | "warning" | "danger" | "info" | "neutral" | "primary";

export const statusTones: Record<Status, BadgeTone> = {
  active: "success",
  inactive: "neutral",
  pending: "warning",
  approved: "success",
  rejected: "danger",
  returned: "info",
  draft: "neutral",
  completed: "success",
  cancelled: "neutral",
  suspended: "danger",
  overdue: "danger",
  submitted: "info",
  under_review: "warning",
  inspection: "warning",
  posted: "success",
  received: "info",
  executed: "success",
  partially_paid: "warning",
  in_transit: "info",
  damaged: "danger",
  reserved: "info",
  delivered: "success",
  in_progress: "info",
  failed: "danger",
  closed: "neutral",
  locked: "danger",
  issued: "info",
  transferred: "info",
  paid: "success",
  partial: "warning",
  unpaid: "danger",
  converted: "success",
  paused: "warning",
  synced: "success",
};